service: fuse-ai-agent

configValidationMode: off
provider:
  name: aws

plugins:
  - serverless-offline

functions:
  webhook:
    handler: dist/index.handler
    timeout: 900
    events:
      - httpApi:
          path: /webhook
          method: post
