name: CI / CD

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Package to AWS Lambda
        run: npm run package

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name fuse-ai-agent-lambda --zip-file fileb://lambda.zip
